name: CI Back-end Main

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'sgcmapi/**'
  workflow_dispatch: #habilita o botão run workflow lá no actions
  workflow_call:
  pull_request: 

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #nome dos steps
        uses: actions/checkout@v4 #caminho para acesso via $GITHUB_WORKSPACE
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test