name: CI Back-end Main

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'sgcmapi/**'
  workflow_dispatch: #habilita o botão run workflow lá no actions
  workflow_call:
  pull_request: 
    paths: 
      - 'sgcmapi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #nome dos steps
        uses: actions/checkout@v4 #caminho para acesso via $GITHUB_WORKSPACE
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Maven Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test

  merge: 
        needs: [build] #se for dois ou mais jobs, coloca aqui, separado por vírgula e só irá fazer o merge quando os dois passarem
        runs-on: ubuntu-latest
        if: github.event_name =='pull_request'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Merge branch
              uses: devmasx/merge-branch@1.4.0
              with:
                type: now
                target_branch: main
                github_token: ${{ github.token }}